### ISSUE TITLE
The positive look ahead should include punctuation marks (, ! ? : ;) 

### ISSUE THREAD

**Issue by Mogztter** [sapegin/textlint-rule-stop-words#15]
Currently, the regular expression use only space, dot followed by a space, dot at the end of the line and end of line:

https://github.com/sapegin/textlint-rule-stop-words/blob/3d1d56bcb8bd5d157ca2269fe8a63b6cb944a0a4/index.js#L124

In other words, it won't match in the following cases:

```
add up?
add up!
add up, and subtract.
add up; and subtract.
add up: 10
```

Using word boundary (`\b`) is probably a bad idea but adding common punctuation marks seems reasonable. What do you think?

**Comment by sapegin** [comment]
Yeah, this sounds like a good idea! Mind sending a pull request? 👾
