### ISSUE TITLE
[proposal] Migrate semantic-release task to GitHub Actions

### ISSUE THREAD

**Issue by Mogztter** [sapegin/textlint-rule-stop-words#20]
Currently, we are using Travis to run: `npx semantic-release` and GitHub Actions for Dependabot.
Would you like to migrate this task to GitHub Actions? Or do you prefer to stay on Travis?

**Comment by sapegin** [comment]
I'm slowly migrating all projects to GitHub Action, so it's a good idea. 

`npx mrm semantic-release` should do most of the work.
