### ISSUE TITLE
Replacement value should be used as-is

### ISSUE THREAD

**Issue by Mogztter** [sapegin/textlint-rule-stop-words#23]
The linter is trying to help by using a capital letter if the match was using standard capitalization (i.e., first letter capitalized).
For instance, given the following definition:

```js
{
  options: {
    words: [['utilize', 'use']],
  }
}
```

It will replace: "Utilize Elm" by "Use Elm" (and not "use Elm" with lowercase "u").

But this does not produce the expected result when working with proper noun.
For instance, if I want to make sure that "reveal.js" is using the correct capitalization (all lowercase):

```js
{
  options: {
    words: [['reveal.js', 'reveal.js']],
  }
}
```

The linter should replace "Reveal.js is great" by "reveal.js is great" but it won't work as expected.
Arguably, both strategies can be useful so we might consider an option to enable/disable this feature.
What do you think?

**Comment by Mogztter** [comment]
One idea would be to declare nouns in `nouns`:

```js
{
  options: {
    words: [['utilize', 'use']],
    nouns: [['reveal.js', 'reveal.js']],
  }
}
```

Another idea would be to introduce a special case when we want to check capitalization:

```js
{
  options: {
    words: [['utilize', 'use']],
    checkCapitalization: [
      'reveal.js',
      'Asciidoctor',
      'Ruby',
      'Node',
      'AsciiDoc'
    ],
  }
}
```

**Comment by sapegin** [comment]
Yup, this behavior is expected: starting sentences with a small letter significantly reduces readability. 

For proper nouns, I'd recommend https://github.com/sapegin/textlint-rule-terminology

**Comment by Mogztter** [comment]
> For proper nouns, I'd recommend sapegin/textlint-rule-terminology

That's awesome, I totally missed it!
Thank you so much for all the work you did on textlint :medal_sports:
